### ISSUE TITLE
Expose binding functionality to scripts

### ISSUE THREAD

**Issue by Rohansi** [SirTony/Mond.BindingEx#4]
Right now bindings can only be created from .NET code but there should be a way to access stuff without having to change the host application. Exposing a way for scripts to call the `Bind` methods would make it easier to interact with the host application without having to change it that much.

I really like how [Jint](https://github.com/sebastienros/jint#accessing-net-assemblies-and-classes) handles this and it should be possible to implement in Mond (aside from `new`, of course) with metamethods.

(Also, why a `new` method instead of `__call` for instantiation?)

**Comment by Rohansi** [comment]
I wrote a little POC for this:

``` csharp
public class InteropLibraries : IMondLibraryCollection
{
    public IEnumerable<IMondLibrary> Create(MondState state)
    {
        yield return new InteropLibrary();
    }
}

public class InteropLibrary : IMondLibrary
{
    public IEnumerable<KeyValuePair<string, MondValue>> GetDefinitions()
    {
        var importNamespace = new MondValue((state, instance, args) => new Namespace(args[0]).ToMond(state));
        yield return new KeyValuePair<string, MondValue>("importNamespace", importNamespace);
    }
}

[MondClass]
class Namespace
{
    private readonly string _path;

    public Namespace(string path)
    {
        _path = path;
    }

    [MondFunction("__get")]
    public MondValue Get(MondState state, MondValue instance, string name)
    {
        var newPath = _path + "." + name;

        var type = Type.GetType(newPath);
        if (type != null)
            return MondObjectBinder.Bind(type, state, MondBindingOptions.AutoLock);

        return new Namespace(newPath).ToMond(state);
    }

    [MondFunction("__call")]
    public MondValue Call(MondState state, MondValue instance, params MondValue[] args)
    {
        var types = args.Select(v => (Type)v.UserData).ToArray();

        var typeName = _path + "`" + types.Length;
        var type = Type.GetType(typeName);
        if (type == null)
            throw new Exception(typeName);

        var boundType = type.MakeGenericType(types);
        return MondObjectBinder.Bind(boundType, state, MondBindingOptions.AutoLock);
    }

    public MondValue ToMond(MondState state)
    {
        MondValue prototype;
        MondClassBinder.Bind<Namespace>(out prototype, state);

        var obj = new MondValue(state);
        obj.UserData = this;
        obj.Prototype = prototype;
        obj.Lock();

        return obj;
    }
}
```

```
var System = importNamespace('System');
var list = System.Collections.Generic.List(System.String).new();
list.Add('hello');
printLn(list.getCount());
```

It needs `MondObjectBinder` to stick the type in the binding's user data to work.

It's missing a few things but they shouldn't be too hard to implement.

**Comment by clarajk** [comment]
I like it. I had thought of including something similar, but I really like this approach.

> (Also, why a `new` method instead of `__call` for instantiation?)

Partly because of personal preference influenced by Ruby (and Rust to a lesser degree). And partly because I believe that the expression `SomeClass.new()` makes it more readily apparent what's happening at a glance without relying on PascalCase versus headlessCamelCase naming conventions to differentiate between normal functions and functions that act as constructors. Python's lack of anything resembling `new` has always been irksome to me I like to avoid similar grammar elsewhere when possible.

More importantly, the above PoC made me realize this library doesn't support the creation of generic types after they've been bound, making them unusable unless the generic parameters are supplied when the type is bound. I think that using the `__call` metamethod for that purpose would be ideal.

i.e.

``` javascript
var generic = SomeGenericClass( System.Double ).new( 3.14 );
```

**Comment by Rohansi** [comment]
One thing we would need to handle is types that have both none and some type arguments, like `Action`. Both `System.Action` and `System.Action(System.String)` need to work.

Also, you're only setting the user data to the type for classes, but it should be set for enums too.
